// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: pride_ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Init
void ui_Init_screen_init(void);
lv_obj_t * ui_Init;
lv_obj_t * ui_Image5;

// CUSTOM VARIABLES


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_voltage_title;
lv_obj_t * ui_coolant_title;
lv_obj_t * ui_cpu_usage_title;
lv_obj_t * ui_ram_usage_title;
lv_obj_t * ui_ram_usage;
lv_obj_t * ui_cpu_usage;
lv_obj_t * ui_obd_status;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image4;
lv_obj_t * ui_bar_voltage;
lv_obj_t * ui_bar_coolant;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;

// SCREEN: ui_Goodbye
void ui_Goodbye_screen_init(void);
lv_obj_t * ui_Goodbye;
lv_obj_t * ui_Main_title;
lv_obj_t * ui_Time_title;
lv_obj_t * ui_Distance_title;
lv_obj_t * ui_Fuel_title;
lv_obj_t * ui_Time_value;
lv_obj_t * ui_Distance_value;
lv_obj_t * ui_Fuel_cons_value;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel3;

// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void switch_to_main_screen(lv_timer_t * timer)
{
    lv_scr_load_anim(ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, false);
    lv_timer_del(timer); // 타이머 삭제
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Init_screen_init();
    ui_Main_screen_init();
    ui_Goodbye_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);

    lv_timer_t * timer = lv_timer_create(switch_to_main_screen, 10000, NULL);
    lv_scr_load(ui_Init);
}