// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: pride_ui

#ifndef _PRIDE_UI_UI_H
#define _PRIDE_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Init
void ui_Init_screen_init(void);
extern lv_obj_t * ui_Init;
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_voltage_title;
extern lv_obj_t * ui_coolant_title;
extern lv_obj_t * ui_cpu_usage_title;
extern lv_obj_t * ui_ram_usage_title;
extern lv_obj_t * ui_ram_usage;
extern lv_obj_t * ui_cpu_usage;
extern lv_obj_t * ui_obd_status;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_init_png);    // assets/init.png
LV_IMG_DECLARE(ui_img_427324742);    // assets/temp (2).png
LV_IMG_DECLARE(ui_img_1638550806);    // assets/voltage (2).png
LV_IMG_DECLARE(ui_img_716095653);    // assets/gauge_bar (2).png

// UI INIT
void ui_init(int splash_count);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
