// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: pride_ui

#include "ui.h"

void ui_Goodbye_screen_init(void)
{
    ui_Goodbye = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Goodbye, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Goodbye, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Goodbye, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_title = lv_label_create(ui_Goodbye);
    lv_obj_set_width(ui_Main_title, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_Main_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_title, 0);
    lv_obj_set_y(ui_Main_title, -86);
    lv_obj_set_align(ui_Main_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_title, "Last Trip Info.");
    lv_obj_set_style_text_color(ui_Main_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_title, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_title = lv_label_create(ui_Goodbye);
    lv_obj_set_width(ui_Time_title, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_Time_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_title, -28);
    lv_obj_set_y(ui_Time_title, -18);
    lv_obj_set_align(ui_Time_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time_title, "Time (HH:MM) : ");
    lv_obj_set_style_text_color(ui_Time_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_title, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Distance_title = lv_label_create(ui_Goodbye);
    lv_obj_set_width(ui_Distance_title, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_Distance_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Distance_title, -25);
    lv_obj_set_y(ui_Distance_title, 16);
    lv_obj_set_align(ui_Distance_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Distance_title, "Distance (Km): ");
    lv_obj_set_style_text_color(ui_Distance_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Distance_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Distance_title, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fuel_title = lv_label_create(ui_Goodbye);
    lv_obj_set_width(ui_Fuel_title, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_Fuel_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fuel_title, -39);
    lv_obj_set_y(ui_Fuel_title, 55);
    lv_obj_set_align(ui_Fuel_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fuel_title, "Avg. Cons. (Km/L): ");
    lv_obj_set_style_text_color(ui_Fuel_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fuel_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fuel_title, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_value = lv_label_create(ui_Goodbye);
    lv_obj_set_width(ui_Time_value, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_Time_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_value, 79);
    lv_obj_set_y(ui_Time_value, -17);
    lv_obj_set_align(ui_Time_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time_value, "03:02");
    lv_obj_set_style_text_color(ui_Time_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Distance_value = lv_label_create(ui_Goodbye);
    lv_obj_set_width(ui_Distance_value, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_Distance_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Distance_value, 83);
    lv_obj_set_y(ui_Distance_value, 18);
    lv_obj_set_align(ui_Distance_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Distance_value, "7718");
    lv_obj_set_style_text_color(ui_Distance_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Distance_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Distance_value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fuel_cons_value = lv_label_create(ui_Goodbye);
    lv_obj_set_width(ui_Fuel_cons_value, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_Fuel_cons_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fuel_cons_value, 87);
    lv_obj_set_y(ui_Fuel_cons_value, 55);
    lv_obj_set_align(ui_Fuel_cons_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fuel_cons_value, "15.6");
    lv_obj_set_style_text_color(ui_Fuel_cons_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fuel_cons_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fuel_cons_value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Goodbye);
    lv_obj_set_width(ui_Panel2, 259);
    lv_obj_set_height(ui_Panel2, 4);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -54);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Goodbye);
    lv_obj_set_width(ui_Panel3, 259);
    lv_obj_set_height(ui_Panel3, 4);
    lv_obj_set_x(ui_Panel3, -1);
    lv_obj_set_y(ui_Panel3, 92);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags



}
