// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: pride_ui

#include "ui.h"

void ui_Init_screen_init(void)
{
    ui_Init = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Init, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Init, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Init, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_Init);
    lv_image_set_src(ui_Image5, &ui_img_init_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 202
    lv_obj_set_x(ui_Image5, -1);
    lv_obj_set_y(ui_Image5, 1);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image5, 200);


}
